[versions]
archunit = "1.5.0"
checkstyle = "14.1.0"
googlejavaformat = "1.36.1"
jacoco = "0.8.15"
junit = "5.14.4"
ktlint = "1.8.0"
paper = "26.2.build.124-stable"
run-paper = "3.0.0"
shadow = "9.6.1"
spotless = "8.10.2"
snakeyaml = "2.2"
luckperms = "5.4"
worldguard = "7.0.9"
vault = "1.7"
placeholderapi = "2.11.6"
miniplaceholders = "2.2.3"
nexo = "0.7.0"
oraxen = "1.182.0"
itemsadder = "3.6.1"
spigot = "1.21.3-R0.1-SNAPSHOT"
adventure-platform = "4.3.4"
adventure = "4.17.0"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms" }
worldguard-api = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
miniplaceholders-api = { module = "io.github.miniplaceholders:miniplaceholders-api", version.ref = "miniplaceholders" }
nexo-api = { module = "com.nexomc:nexo", version.ref = "nexo" }
oraxen-api = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
itemsadder-api = { module = "com.github.LoneDev6:API-ItemsAdder", version.ref = "itemsadder" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
